// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-8QNeFqc-MOc3IjdETA3QPiLtMi12M7M',
    appId: '1:938794883536:web:09bb535e05f4ae502fc1d5',
    messagingSenderId: '938794883536',
    projectId: 'projectpab-58416',
    authDomain: 'projectpab-58416.firebaseapp.com',
    storageBucket: 'projectpab-58416.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyXD1nE5wZmFdVpVksHlL4cRY9BYzVwtk',
    appId: '1:938794883536:android:50fbf14d89c29dae2fc1d5',
    messagingSenderId: '938794883536',
    projectId: 'projectpab-58416',
    storageBucket: 'projectpab-58416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3rJVgEbPyl-DCogpFL-oz0KcqLsdvvwc',
    appId: '1:938794883536:ios:56670f85381a4a472fc1d5',
    messagingSenderId: '938794883536',
    projectId: 'projectpab-58416',
    storageBucket: 'projectpab-58416.firebasestorage.app',
    iosBundleId: 'com.example.akiflash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3rJVgEbPyl-DCogpFL-oz0KcqLsdvvwc',
    appId: '1:938794883536:ios:56670f85381a4a472fc1d5',
    messagingSenderId: '938794883536',
    projectId: 'projectpab-58416',
    storageBucket: 'projectpab-58416.firebasestorage.app',
    iosBundleId: 'com.example.akiflash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-8QNeFqc-MOc3IjdETA3QPiLtMi12M7M',
    appId: '1:938794883536:web:7541d6d09bacac932fc1d5',
    messagingSenderId: '938794883536',
    projectId: 'projectpab-58416',
    authDomain: 'projectpab-58416.firebaseapp.com',
    storageBucket: 'projectpab-58416.firebasestorage.app',
  );
}
